/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sdgsweden;

/**
 * 
 * @author winte
 */
public class AndraProjekt extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AndraProjekt.class.getName());

    /**
     * Creates new form AndraProjekt
     */
    public AndraProjekt() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBeskrivning = new javax.swing.JLabel();
        ButtonOkMedAlt = new javax.swing.JButton();
        rbtnLaggTill = new javax.swing.JRadioButton();
        rbtnTaBort = new javax.swing.JRadioButton();
        rbtnAndra = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblBeskrivning.setText("Administration av projekt");

        ButtonOkMedAlt.setText("Gå vidare");
        ButtonOkMedAlt.addActionListener(this::ButtonOkMedAltActionPerformed);

        rbtnLaggTill.setText("Lägg till nytt projekt");

        rbtnTaBort.setText("Ta bort projekt");

        rbtnAndra.setText("Ändra i projekt");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ButtonOkMedAlt)
                    .addComponent(rbtnTaBort)
                    .addComponent(rbtnLaggTill)
                    .addComponent(rbtnAndra)
                    .addComponent(lblBeskrivning))
                .addContainerGap(242, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(lblBeskrivning)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtnLaggTill)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtnTaBort)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtnAndra)
                .addGap(18, 18, 18)
                .addComponent(ButtonOkMedAlt)
                .addContainerGap(119, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonOkMedAltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonOkMedAltActionPerformed

    if(rbtnLaggTill.isSelected()){
        new LaggaTillProjektJFrame().setVisible(true);
    }else if (rbtnTaBort.isSelected()){
      new TaBortProjektJFrame().setVisible(true); 
    }else if (rbtnAndra.isSelected()){
       new AndraEttProjektJFrame().setVisible(true);
    }
    this.dispose(); //Stänger valfönstret
    }//GEN-LAST:event_ButtonOkMedAltActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AndraProjekt().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonOkMedAlt;
    private javax.swing.JLabel lblBeskrivning;
    private javax.swing.JRadioButton rbtnAndra;
    private javax.swing.JRadioButton rbtnLaggTill;
    private javax.swing.JRadioButton rbtnTaBort;
    // End of variables declaration//GEN-END:variables
}
